### PR TITLE
Update ContainerService Managed Clusters to 2019-08-01

### PR DESCRIPTION
**Pull request by xizhamsft**
updating containerservice managed clusters api to the latest api version (2019-08-01)

### CODE REVIEW

**Comment by xizhamsft** [comment]
@balag0 , could you take a look of this PR and merge it if no problem? I simply updated the swagger to the latest.

**Comment by balag0** [comment]
Merged. Please verify on https://resources-staging.azure.com

**Comment by xizhamsft** [comment]
@balag0 , it works perfectly. Thanks a lot!

**Comment by balag0** [comment]
Great. We will swap the changes to the prod site before Monday.

**Pull request merged**
