### PR TITLE
 Initial support for overriding query parameters

### PR DESCRIPTION
**Pull request by bala16**
Expose required query parameters defined in swagger. Use default value for api-version from swagger.

### CODE REVIEW

**Comment by bala16** [comment]
Dummy API with 2 required parameters api-version and $filter will be displayed as
image

**Comment by davidebbo** [comment]
So API version would always be editable? The slightly strange thing is that the list of API may differ from version to version, but here the list would always be driven from a given version.

**Comment by bala16** [comment]
Yes. API version will always be editable (and pre filled with the api version from swagger). Idea is that users who want to override the apiversion (or any other required query parameter for a given API ) have the ability to do so , for others there is no impact. 
It is true that when API version changes the API itself might change, but the default api version pre filled will always work.  At the least this change can support those APIs for which the interface hasn't changed between api versions.

**Comment by davidebbo** [comment]
Sounds good, I can see that being useful in some scenarios. If you want to get fancier later, you could offer a drop down with the available versions for the API, which you can get from ARM (at least for registered resources). But let's start with what you have :)

**Pull request closed without merging**
