### PR TITLE
Add and update Azure Front Door Swagger files

### PR DESCRIPTION
**Pull request by johndowns**
Swagger files updated in this pull request:

* Updated Microsoft.Cdn to add missing definitions for schema version 2020-09-01

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/projectkudu/AzureResourceExplorer?pullRequest=318) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/projectkudu/AzureResourceExplorer?pullRequest=318) before we can accept your contribution.<br/><br/>:x: johndowns [sign now](https://cla.dotnetfoundation.org/projectkudu/AzureResourceExplorer?pullRequest=318)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/projectkudu/AzureResourceExplorer?pullRequest=318) it.</sub>

**Review by balag0 — APPROVED** [review]

**Comment by balag0** [comment]
@johndowns Change deployed to https://resources-staging.azure.com/
Please verify before we deploy to the prod site. Thanks

**Comment by johndowns** [comment]
Thanks @balag0 - yes I can see the resource definitions now appear on the staging site!

Do you know what the timeline is for this to be deployed to the production resources.azure.com and also to the 'Resource Explorer' blade in the Azure portal?

**Comment by balag0** [comment]
Great, The blade in Azure Portal is not related to this project and I am not sure how that works.
We plan deploy to resources.azure.com this friday.

**Pull request merged**
