### PR TITLE
Added Kusto swagger

### PR DESCRIPTION
**Pull request by saguiitay**

### CODE REVIEW

**Comment by saguiitay** [comment]
@balag0 , could you take a look of this PR and merge it if no problem?

**Comment by balag0** [comment]
@saguiitay Merged and available at https://resources-staging.azure.com/
Please verify before we move it to the prod site.

**Comment by saguiitay** [comment]
@balag0 I can't see the Kusto provider in the staging environment (I can see my resource in the list of resources). Did I miss something?

**Comment by balag0** [comment]
Can you post a screenshot of what you are seeing. Where are you seeing the resource? 
Is there a easy way for me to repro this? (I don't have any kusto resources under any of my subscriptions currently)

**Comment by saguiitay** [comment]
image
image
image

**Comment by saguiitay** [comment]
@balag0 any update?

**Comment by saguiitay** [comment]
@balag0 I think you need to register the Microsoft.Kusto provider to subscription 1402be24-4f35-4ab7-a212-2cd496ebdf14, and invoke `UpdateProvidersList.ps1`, in order to update `ProvidersList.json`

**Comment by saguiitay** [comment]
@balag0 ping?

**Comment by balag0** [comment]
We no longer use UpdateProvidersList.ps1 to update swaggers. 

It is not clear what node you are under from the screenshot. Make sure you are under subscriptions/<SubscriptionID>/resourcegroups/<ResourceGroup>/Providers/...

Also check if you are getting Microsoft.Kusto resources when you call the following arm api for your subscription
subscriptions/<Subscription-Id>/resources?api-version=<api-version>

**Comment by saguiitay** [comment]
When I perform a GET operation at `https://management.azure.com/subscriptions/fbccad30-f0ed-4ac4-9497-93bf6141062f/providers?api-version=2017-05-10` I can see the `Microsoft.Kusto` provider: 
``` json
{
      "id": "/subscriptions/fbccad30-f0ed-4ac4-9497-93bf6141062f/providers/Microsoft.Kusto",
      "namespace": "Microsoft.Kusto",
      "authorizations": [{
          "applicationId": "2746ea77-4702-4b45-80ca-3c97e680e8b7",
          "roleDefinitionId": "dd9d4347-f397-45f2-b538-85f21c90037c"
        }
      ],
      "resourceTypes": [{
          "resourceType": "clusters",
          "locations": [
            "Central US",
            "West Europe",
            "North Europe",
            "East US 2",
            "West Central US",
            "Germany West Central",
            "West US",
            "Southeast Asia",
            "East US",
            "South Central US",
            "North Central US",
            "East Asia",
            "Japan East",
            "Canada Central",
            "UK South",
            "Australia East",
            "Brazil South",
            "Japan West",
            "South India",
            "Central India",
            "West India",
            "Canada East",
            "Korea Central",
            "France Central",
            "UK West",
            "Korea South",
            "France South",
            "Australia Southeast",
            "South Africa North",
            "South Africa West",
            "Australia Central",
            "Switzerland North",
            "UAE North",
            "West US 2"
          ],
          "apiVersions": [
            "2019-11-09",
            "2019-09-07",
            "2019-05-15",
            "2019-01-21",
            "2018-09-07-preview",
            "2017-09-07-privatepreview"
          ],
    ...
    "registrationState": "Registered"
```

However, I don't see the Micosoft.Kusto provider in the treeview under the `providers` node

**Comment by balag0** [comment]
What about the api I mentioned above (/resources).

**Comment by saguiitay** [comment]
Yes. When I do the GET request on `https://management.azure.com/subscriptions/fbccad30-f0ed-4ac4-9497-93bf6141062f/resources?api-version=2017-05-10` I can see my resource:

```json
{
      "id": "/subscriptions/fbccad30-f0ed-4ac4-9497-93bf6141062f/resourceGroups/itsagui-tests/providers/Microsoft.Kusto/clusters/itsaguimsi5",
      "name": "itsaguimsi5",
      "type": "Microsoft.Kusto/clusters",
      "sku": {
        "name": "Standard_D11_v2",
        "tier": "Standard",
        "capacity": 2
      },
      "location": "westus2",
      "tags": {}
    },
```

**Pull request merged**
